### PR TITLE
Use less prescriptive shebang

### PR DESCRIPTION
**Pull request by jeffbyrnes**
In this way, the user’s version of bash is used, rather than forcing the system version to be used.

### CODE REVIEW

**Comment by phallstrom** [comment]
Not that I'm opposed, but why?  Seems like I might be better off ensuring it's running against a known version of bash?  Then again, I suppose that version changes from OS version to OS version and I don't test that...

**Comment by jeffbyrnes** [comment]
@phallstrom that’s why the `/usr/bin/env bash` shebang is always a good idea, it [makes a script more portable](http://www.cyberciti.biz/tips/finding-bash-perl-python-portably-using-env.html).

**Comment by phallstrom** [comment]
Yeah, I get that for a script that may be installed on OSX, Linux, etc, but since this will always be on OSX and `/bin/bash` will always exist, it seems like making this change me introduce larger issues -- someone running an odd version of bash, or something called bash that isn't bash.

I guess my question is... what is it you're losing by me forcing you to run /bin/bash here?

**Comment by jeffbyrnes** [comment]
Nothing at all. And you’re probably right, it’s highly unlikely that `/usr/bin/bash` will ever not be the OS X system version of `bash`.

**Pull request closed without merging**
